name: ncu action
description: npm package update action using ncu
author: SotaSuzuki
outputs:
  has_update:
    description: whether update available or not
  formatted_as_json:
    description: new version information formatted as json
  formatted_as_columns:
    description: new version information formatted as columns for markdown table
runs:
  using: node12
  main: dist/index.js

